Repository BlueQuartzSoftware/simplnx, pull requests merged in 2023-07, with the labels that each got.

#626 BUG: Fix FindArrayStatistics when computing std dev by index w/o the mean or length options
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/FindArrayStatistics.cpp
Labels: bug

#628 ENH: Extend CopyFeatureArrayToElementArray filter to work for multiple feature arrays at once
  pipelines/PorosityAnalysis.d3dpipeline
  src/Plugins/ComplexCore/src/ComplexCore/Filters/CopyFeatureArrayToElementArray.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/CopyFeatureArrayToElementArray.hpp
  src/Plugins/ComplexCore/test/CopyFeatureArrayToElementArrayTest.cpp
  src/Plugins/ITKImageProcessing/pipelines/(02) Image Segmentation.d3dpipeline
  src/complex/Parameters/MultiArraySelectionParameter.cpp
Labels: enhancement

#636 BUG: Fixing incorrect BoundingBox construction (wrong min/max order).
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/FindBiasedFeatures.cpp
  src/complex/DataStructure/Geometry/ImageGeom.cpp
  src/complex/Utilities/ImageRotationUtilities.cpp
Labels: bug

#630 BUG: FindArrayStats & RobustAutomaticThreshold
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/FindArrayStatistics.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/RobustAutomaticThreshold.cpp
Labels: bug, enhancement

#634 BUG: Add missing unit tests
  src/Plugins/ComplexCore/src/ComplexCore/Filters/IdentifySample.cpp
  src/Plugins/ComplexCore/test/CMakeLists.txt
  src/Plugins/ComplexCore/test/IdentifySampleTest.cpp
  src/Plugins/OrientationAnalysis/docs/ReadAngDataFilter.md
  src/Plugins/OrientationAnalysis/docs/ReadCtfDataFilter.md
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ReadAngData.cpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ReadAngData.hpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ReadCtfData.cpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ReadCtfData.hpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/ReadAngDataFilter.cpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/ReadAngDataFilter.hpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/ReadCtfDataFilter.cpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/ReadCtfDataFilter.hpp
  src/Plugins/OrientationAnalysis/test/CMakeLists.txt
  src/Plugins/OrientationAnalysis/test/ReadAngDataTest.cpp
  src/Plugins/OrientationAnalysis/test/ReadCtfDataTest.cpp
Labels: bug

#638 ENH: Organize target groups for the Download/Copy/Extract targets
  CMakeLists.txt
  cmake/Utility.cmake
  src/Plugins/ComplexCore/CMakeLists.txt
  src/Plugins/ITKImageProcessing/CMakeLists.txt
  src/Plugins/OrientationAnalysis/CMakeLists.txt
Labels: enhancement

#648 BUG: Correctly determine if a drive does not exist (Windows)
  src/Plugins/ComplexCore/test/WriteBinaryDataTest.cpp
Labels: bug
