Repository BlueQuartzSoftware/simplnx, pull requests merged in 2023-01, with the labels that each got.

#412 RotateSampleRefFrame: Fix unit test to compare output to exemplar arrays
  src/Plugins/ComplexCore/test/CMakeLists.txt
  src/Plugins/ComplexCore/test/RotateSampleRefFrameTest.cpp
Labels: bug

#367 FILTER: PartitionGeometry
  CMakeLists.txt
  src/Plugins/ComplexCore/CMakeLists.txt
  src/Plugins/ComplexCore/docs/PartitionGeometryFilter.md
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/PartitionGeometry.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/PartitionGeometry.hpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/PartitionGeometryFilter.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/PartitionGeometryFilter.hpp
  src/Plugins/ComplexCore/test/CMakeLists.txt
  src/Plugins/ComplexCore/test/PartitionGeometryTest.cpp
  src/complex/DataStructure/Geometry/INodeGeometry0D.cpp
  src/complex/DataStructure/Geometry/INodeGeometry0D.hpp
  src/complex/DataStructure/Geometry/RectGridGeom.cpp
  src/complex/DataStructure/Geometry/RectGridGeom.hpp
  src/complex/Utilities/GeometryUtilities.hpp
Labels: Filter

#416 FILTER: Generate Color Table
  CMakeLists.txt
  src/Plugins/ComplexCore/CMakeLists.txt
  src/Plugins/ComplexCore/docs/GenerateColorTableFilter.md
  src/Plugins/ComplexCore/src/ComplexCore/ComplexCoreLegacyUUIDMapping.hpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/GenerateColorTable.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/GenerateColorTable.hpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/GenerateColorTableFilter.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/GenerateColorTableFilter.hpp
  src/Plugins/ComplexCore/test/CMakeLists.txt
  src/Plugins/ComplexCore/test/GenerateColorTableTest.cpp
  src/complex/Parameters/GenerateColorTableParameter.cpp
  src/complex/Parameters/GenerateColorTableParameter.hpp
  src/complex/Utilities/ColorPresetsUtilities.hpp
Labels: Filter

#417 BUG: Stop duplicate plugin loading in PipelineRunner
  src/PipelineRunner/src/PipelineRunner.cpp
Labels: bug

#430 Set the debug postfix in 1 spot and use that variable throughout cmake
  CMakeLists.txt
  cmake/MacOSXBundleInfo.plist.in
  cmake/Plugin.cmake
  src/PipelineRunner/CMakeLists.txt
  src/complex/Core/Application.cpp
  src/complex/Utilities/StringUtilities.hpp
Labels: enhancement

#424 DREAM3D files created during unit tests should be readable by DREAM.3D
  test/UnitTestCommon/include/complex/UnitTest/UnitTestCommon.hpp
Labels: enhancement

#426 FILTER: Move AlignSectionsFeatureCentroid to ComplexCore plugin
  CMakeLists.txt
  src/Plugins/ComplexCore/CMakeLists.txt
  src/Plugins/ComplexCore/docs/AlignSectionsFeatureCentroidFilter.md
  src/Plugins/ComplexCore/src/ComplexCore/ComplexCoreLegacyUUIDMapping.hpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/AlignSectionsFeatureCentroid.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/AlignSectionsFeatureCentroid.hpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignSectionsFeatureCentroidFilter.cpp
  src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignSectionsFeatureCentroidFilter.hpp
  src/Plugins/ComplexCore/test/AlignSectionsFeatureCentroidTest.cpp
  src/Plugins/ComplexCore/test/CMakeLists.txt
Labels: enhancement, Filter
