Repository BlueQuartzSoftware/simplnx, pull requests merged in 2024-02, with the labels that each got.

#844 BUG: fix IParallelAlgorithm not running in parallel
  src/simplnx/Utilities/IParallelAlgorithm.cpp
Labels: bug

#838 FILTERS: Added CalculateHistogram, InterpolateGridData, and CliReader Python filters.
  .gitignore
  src/Plugins/SimplnxCore/wrapping/python/simplnxpy.cpp
  src/simplnx/Filter/Actions/CreateGeometry1DAction.hpp
  src/simplnx/Filter/Actions/CreateGeometry2DAction.hpp
  src/simplnx/Filter/Actions/CreateGeometry3DAction.hpp
  src/simplnx/Filter/Actions/CreateRectGridGeometryAction.cpp
  wrapping/python/plugins/DataAnalysisToolkit/CalculateHistogramFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/CliReaderFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/InterpolateGridDataFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/Plugin.py
  wrapping/python/plugins/DataAnalysisToolkit/__init__.py
  wrapping/python/plugins/DataAnalysisToolkit/docs/CalculateHistogramFilter.md
  wrapping/python/plugins/DataAnalysisToolkit/docs/CliReaderFilter.md
  wrapping/python/plugins/DataAnalysisToolkit/docs/InterpolateGridDataFilter.md
  wrapping/python/plugins/DataAnalysisToolkit/utilities/__init__.py
  wrapping/python/plugins/DataAnalysisToolkit/utilities/cli_tools.py
Labels: Filter

#837 DOCS: Implement python developer documentation including filter examples and a tutorial
  .all-contributorsrc
  CMakeLists.txt
  src/Plugins/SimplnxCore/docs/GeneratePythonSkeletonFilter.md
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/GeneratePythonSkeletonFilter.cpp
  src/Plugins/SimplnxCore/wrapping/python/simplnxpy.cpp
  wrapping/python/docs/index_template.rst
  wrapping/python/docs/source/Developer_API.rst
  wrapping/python/docs/source/Images/Generate_Python_Plugin.png
  wrapping/python/docs/source/Images/Generate_Python_Plugin_2.png
  wrapping/python/docs/source/Python_Introduction.rst
  wrapping/python/docs/source/ReleaseNotes_110.rst
  wrapping/python/docs/source/User_API.rst
  wrapping/python/docs/source/Writing_A_New_Python_Filter.rst
  wrapping/python/docs/source/conf.py
  wrapping/python/plugins/ExamplePlugin/CreateArray.py
  wrapping/python/plugins/ExamplePlugin/ExampleFilter1.py
  wrapping/python/plugins/ExamplePlugin/ExampleFilter2.py
  wrapping/python/plugins/ExamplePlugin/InitializeData.py
  wrapping/python/plugins/ExamplePlugin/Plugin.py
  wrapping/python/plugins/ExamplePlugin/TemplateFilter.py
  wrapping/python/plugins/ExamplePlugin/__init__.py
  wrapping/python/plugins/TestPlugin/Plugin.py
  wrapping/python/plugins/TestPlugin/__init__.py
Labels: documentation

#863 BUG: Fix issue creating proper sized Attribute Matrix for Ensemble Data
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ReadH5Ebsd.cpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/ReadH5EbsdFilter.cpp
Labels: bug

#872 Use consistent simplnx alias, tweak parameter declaration sections.
  wrapping/python/docs/source/DataObjects.rst
  wrapping/python/docs/source/Developer_API.rst
  wrapping/python/docs/source/Geometry.rst
  wrapping/python/docs/source/Overview.rst
  wrapping/python/docs/source/Python_Introduction.rst
  wrapping/python/docs/source/ReleaseNotes_110.rst
  wrapping/python/docs/source/ReleaseNotes_120.rst
  wrapping/python/docs/source/ReleaseNotes_121.rst
  wrapping/python/docs/source/User_API.rst
  wrapping/python/docs/source/Writing_A_New_Python_Filter.rst
  wrapping/python/examples/pipelines/Incomplete/ImportBrukerNanoEspritData.py
  wrapping/python/examples/pipelines/Incomplete/ImportEdaxOIMData.py
  wrapping/python/examples/scripts/Combine_STL_Files.py
  wrapping/python/examples/scripts/Import_STL_File.py
  wrapping/python/plugins/DataAnalysisToolkit/CalculateHistogramFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/CliReaderFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/InterpolateGridDataFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/Plugin.py
  wrapping/python/plugins/ExamplePlugin/ExampleFilter1.py
  wrapping/python/plugins/ExamplePlugin/ExampleFilter2.py
Labels: documentation
