Repository BlueQuartzSoftware/simplnx, pull requests merged in 2024-09, with the labels that each got.

#1065 BUG: SliceTriangleGeometry - fix crash when RegionIds are not used.
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/SliceTriangleGeometry.cpp
Labels: bug

#1067 ENH: Add support for poly lines to CLIReader.
  wrapping/python/plugins/NXDataAnalysisToolkit/docs/CliReaderFilter.md
  wrapping/python/plugins/NXDataAnalysisToolkit/src/NXDataAnalysisToolkit/CliReaderFilter.py
Labels: enhancement

#1078 ENH: Update Read CSV Filter caching to handle modified files.
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ReadCSVFileFilter.cpp
Labels: enhancement

#1084 Better preflight values for CreateDataArrayAdvanced & InitializeData.
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/InitializeData.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/InitializeData.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/CreateDataArrayAdvancedFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/InitializeDataFilter.cpp
Labels: enhancement

#1072 FILTER: Concatenate Data Arrays
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/docs/CombineAttributeArraysFilter.md
  src/Plugins/SimplnxCore/docs/ConcatenateDataArraysFilter.md
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/ConcatenateDataArrays.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/ConcatenateDataArrays.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ConcatenateDataArraysFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ConcatenateDataArraysFilter.hpp
  src/Plugins/SimplnxCore/test/CMakeLists.txt
  src/Plugins/SimplnxCore/test/ConcatenateDataArraysTest.cpp
Labels: Filter

#1086 ENH: Flip the incoming data across the X axis in PeregrineHDF5Reader.
  wrapping/python/plugins/NXDataAnalysisToolkit/src/NXDataAnalysisToolkit/ReadPeregrineHDF5File.py
Labels: enhancement
