Repository BlueQuartzSoftware/simplnx, pull requests merged in 2024-05, with the labels that each got.

#938 BUG: WriteAsciiData-Add preflight checks for empty paths.
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/WriteASCIIDataFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/WriteDREAM3DFilter.cpp
  src/simplnx/Parameters/FileSystemPathParameter.cpp
Labels: bug

#945 BUG: Fix ITKImageProcessing filter UUIDs.
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKAbsImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKAcosImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKAdaptiveHistogramEqualizationImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKAsinImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKAtanImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryContourImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryDilateImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryErodeImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryMorphologicalClosingImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryMorphologicalOpeningImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryOpeningByReconstructionImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryProjectionImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryThinningImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBinaryThresholdImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKBlackTopHatImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKClosingByReconstructionImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKCosImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKDilateObjectMorphologyImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKDiscreteGaussianImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKErodeObjectMorphologyImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKExpImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKExpNegativeImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKGradientMagnitudeImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKGrayscaleDilateImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKGrayscaleErodeImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKGrayscaleFillholeImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKGrayscaleGrindPeakImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKGrayscaleMorphologicalClosingImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKGrayscaleMorphologicalOpeningImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKHConvexImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKHMaximaImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKHMinimaImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKIntensityWindowingImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKInvertIntensityImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKLabelContourImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKLog10ImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKLogImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKMedianImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKMorphologicalGradientImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKMorphologicalWatershedImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKNormalizeImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKNotImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKOpeningByReconstructionImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKOtsuMultipleThresholdsImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKRelabelComponentImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKRescaleIntensityImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKSigmoidImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKSignedMaurerDistanceMapImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKSinImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKSqrtImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKSquareImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKTanImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKThresholdImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKValuedRegionalMaximaImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKValuedRegionalMinimaImageFilter.hpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKWhiteTopHatImageFilter.hpp
  wrapping/python/docs/generate_sphinx_docs.cpp
Labels: bug

#946 ENH: CLI Reader Bounding Box
  wrapping/python/plugins/DataAnalysisToolkit/CliReaderFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/common/Result.py
  wrapping/python/plugins/DataAnalysisToolkit/docs/CliReaderFilter.md
  wrapping/python/plugins/DataAnalysisToolkit/utilities/cli_tools.py
Labels: enhancement

#960 ENH: CliReaderFilter-Add edge-bounding box intersection options
  wrapping/python/plugins/DataAnalysisToolkit/CliReaderFilter.py
  wrapping/python/plugins/DataAnalysisToolkit/utilities/__init__.py
  wrapping/python/plugins/DataAnalysisToolkit/utilities/cli_tools.py
Labels: enhancement

#951 DOC: Add Python documentation for all Actions.
  wrapping/python/docs/source/Developer_API.rst
Labels: documentation

#959 BUG: Fix crashes in SIMPL Json to SIMPLNX filter
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKImageReaderFilter.cpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/GenerateFZQuaternionsFilter.cpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/GenerateFeatureFaceMisorientationFilter.hpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/OrientationAnalysisLegacyUUIDMapping.hpp
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/OrientationAnalysisPlugin.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/ExecuteProcess.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/GenerateColorTableFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/MultiThresholdObjectsFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ReadDREAM3DFilter.cpp
  src/simplnx/Filter/IFilter.cpp
  src/simplnx/Pipeline/PipelineFilter.cpp
  src/simplnx/Utilities/Parsing/DREAM3D/Dream3dIO.cpp
  src/simplnx/Utilities/Parsing/DREAM3D/Dream3dIO.hpp
  test/CMakeLists.txt
  test/SimplJsonConversionTest.cpp
Labels: bug

#964 ENH: Factor Out EliminateDuplicateNodes and FillDataArray, Add Sub-Volume Reading, and Improve Error Reporting
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKImportImageStackFilter.cpp
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKMhaFileReaderFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/ReadStlFile.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/ReadStlFile.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ReadHDF5DatasetFilter.cpp
  src/Plugins/SimplnxCore/wrapping/python/simplnxpy.cpp
  src/simplnx/DataStructure/AbstractDataStore.hpp
  src/simplnx/DataStructure/IO/HDF5/DataStoreIO.hpp
  src/simplnx/DataStructure/IO/HDF5/ScalarDataIO.hpp
  src/simplnx/Utilities/DataArrayUtilities.hpp
  src/simplnx/Utilities/GeometryUtilities.cpp
  src/simplnx/Utilities/GeometryUtilities.hpp
  src/simplnx/Utilities/ImageRotationUtilities.hpp
  src/simplnx/Utilities/Parsing/DREAM3D/Dream3dIO.cpp
  src/simplnx/Utilities/Parsing/HDF5/H5Support.hpp
  src/simplnx/Utilities/Parsing/HDF5/Readers/DatasetReader.cpp
  src/simplnx/Utilities/Parsing/HDF5/Readers/DatasetReader.hpp
Labels: enhancement

#973 DOC: Fix various documentation bugs.
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKLabelContourImageFilter.cpp
  src/Plugins/OrientationAnalysis/docs/Images/ComputeFaceIPFColoring.png
  src/Plugins/OrientationAnalysis/docs/ReadH5EspritDataFilter.md
  src/Plugins/OrientationAnalysis/docs/ReadH5OimDataFilter.md
  src/Plugins/OrientationAnalysis/docs/ReadH5OinaDataFilter.md
  wrapping/python/docs/source/Developer_API.rst
  wrapping/python/docs/source/User_API.rst
Labels: documentation

#965 FILTER: Create Peregrine Reader Filter (Python)
  wrapping/python/plugins/DataAnalysisToolkit/Plugin.py
  wrapping/python/plugins/DataAnalysisToolkit/ReadPeregrineHDF5File.py
  wrapping/python/plugins/DataAnalysisToolkit/__init__.py
  wrapping/python/plugins/DataAnalysisToolkit/common/__init__.py
  wrapping/python/plugins/DataAnalysisToolkit/docs/ReadPeregrineHDF5FileFilter.md
  wrapping/python/plugins/DataAnalysisToolkit/environment.yml
Labels: Filter

#977 BUG: ReadCSVFileFilter-Replace illegal characters in headers.
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ReadCSVFileFilter.cpp
  src/Plugins/SimplnxCore/test/ReadCSVFileTest.cpp
  src/simplnx/DataStructure/DataPath.cpp
  src/simplnx/Utilities/StringUtilities.hpp
Labels: bug

#970 ENH: Python Plugin Environment Files
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginEnvironmentTemplate.py
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginSourceTemplate.in.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginTemplateFile.hpp
  wrapping/python/plugins/ExamplePlugin/environment.yml
Labels: enhancement
