Repository BlueQuartzSoftware/simplnx, pull requests merged in 2024-03, with the labels that each got.

#877 ENH: GeneratePythonFilter-Crashing fixed, Generation Fixed, headers split
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginSourceTemplate.in.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginTemplateFile.hpp
  wrapping/python/plugins/DataAnalysisToolkit/NPSortArray.py
  wrapping/python/plugins/DataAnalysisToolkit/Plugin.py
  wrapping/python/plugins/DataAnalysisToolkit/__init__.py
Labels: bug, enhancement

#890 ENH : Add support for getting the pipeline json object from a dream3d file
  src/simplnx/Pipeline/Pipeline.cpp
  src/simplnx/Pipeline/Pipeline.hpp
  src/simplnx/Utilities/Parsing/DREAM3D/Dream3dIO.cpp
  src/simplnx/Utilities/Parsing/DREAM3D/Dream3dIO.hpp
Labels: enhancement

#891 BUG: Return invalid Result<> if size of directory is requested.
  src/simplnx/Utilities/FileUtilities.cpp
Labels: bug

#897 FILTER : ExtractPipelineToFile
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/docs/ExtractPipelineToFileFilter.md
  src/Plugins/SimplnxCore/pipelines/ExtractPipelineToFile.d3dpipeline
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ExtractPipelineToFileFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ExtractPipelineToFileFilter.hpp
  src/Plugins/SimplnxCore/test/CMakeLists.txt
  src/Plugins/SimplnxCore/test/ExtractPipelineToFileTest.cpp
  src/simplnx/Pipeline/Pipeline.hpp
Labels: Filter

#896 ENH: GeneratePythonPlugin can generate batch/shell init file.
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/GeneratePythonSkeleton.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/GeneratePythonSkeleton.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/GeneratePythonSkeletonFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/GeneratePythonSkeletonFilter.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonFilterTemplate.py
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginSourceTemplate.in.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginTemplate.bat
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginTemplate.sh
  src/Plugins/SimplnxCore/src/SimplnxCore/utils/PythonPluginTemplateFile.hpp
  src/Plugins/SimplnxCore/wrapping/python/simplnxpy.cpp
Labels: enhancement
