Repository BlueQuartzSoftware/simplnx, pull requests merged in 2024-06, with the labels that each got.

#981 PYTHON: Add helper methods to be able to easily create all the geometries.
  src/Plugins/SimplnxCore/wrapping/python/simplnxpy.cpp
  wrapping/python/docs/source/User_API.rst
Labels: enhancement

#925 DOCS: Create a short tutorial about writing basic python + simplnx integration
  conda/conda_build_config.yaml
  conda/meta.yaml
  conda/recipe.yaml
  src/Plugins/ITKImageProcessing/src/ITKImageProcessing/Filters/ITKLabelContourImageFilter.cpp
  src/Plugins/TestOne/src/TestOne/Filters/ExampleFilter2Filter.cpp
  wrapping/python/ReadMe.md
  wrapping/python/docs/generate_sphinx_docs.cpp
  wrapping/python/docs/index_template.rst
  wrapping/python/docs/source/Developer_API.rst
  wrapping/python/docs/source/Images/Parameters/ArrayCreationParameter.png
  wrapping/python/docs/source/Images/Parameters/ArraySelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/ArrayThresholdsParameter.png
  wrapping/python/docs/source/Images/Parameters/AttributeMatrixSelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/BoolParameter.png
  wrapping/python/docs/source/Images/Parameters/CalculatorParameter.png
  wrapping/python/docs/source/Images/Parameters/ChoicesParameter.png
  wrapping/python/docs/source/Images/Parameters/CreateColorMapParameter.png
  wrapping/python/docs/source/Images/Parameters/DataGroupCreationParameter.png
  wrapping/python/docs/source/Images/Parameters/DataGroupSelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/DataObjectNameParameter.png
  wrapping/python/docs/source/Images/Parameters/DataPathSelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/DataTypeParameter.png
  wrapping/python/docs/source/Images/Parameters/Dream3dImportParameter.png
  wrapping/python/docs/source/Images/Parameters/DynamicTableParameter.png
  wrapping/python/docs/source/Images/Parameters/EnsembleInfoParameter.png
  wrapping/python/docs/source/Images/Parameters/FileSystemPathParameter.png
  wrapping/python/docs/source/Images/Parameters/GeneratedFileListParameter.png
  wrapping/python/docs/source/Images/Parameters/GeometrySelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/MultiArraySelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/MultiPathSelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/NeighborListSelectionParameter.png
  wrapping/python/docs/source/Images/Parameters/NumericTypeParameter.png
  wrapping/python/docs/source/Images/Parameters/NumericalParameter.png
  wrapping/python/docs/source/Images/Parameters/ReadCSVFileParameter.png
  wrapping/python/docs/source/Images/Parameters/ReadHDF5DatasetParameter.png
  wrapping/python/docs/source/Images/Parameters/StringParameter.png
  wrapping/python/docs/source/Images/Parameters/VectorParameter.png
  wrapping/python/docs/source/Images/Tutorial_1_Image_1.png
  wrapping/python/docs/source/Images/Tutorial_3/parameters_1.png
  wrapping/python/docs/source/Images/Tutorial_3/parameters_2.png
  wrapping/python/docs/source/Images/Tutorial_3/parameters_3.png
  wrapping/python/docs/source/Images/Tutorial_3/parameters_4.png
  wrapping/python/docs/source/Images/Tutorial_3/parameters_5.png
  wrapping/python/docs/source/Images/Tutorial_3/parameters_6.png
  wrapping/python/docs/source/Images/Tutorial_3/plugin_generated.png
  wrapping/python/docs/source/Images/Tutorial_3/plugin_loading_1.png
  wrapping/python/docs/source/Images/Tutorial_3/plugin_loading_2.png
  wrapping/python/docs/source/Images/Tutorial_3/plugin_loading_3.png
  wrapping/python/docs/source/Python_Introduction.rst
  wrapping/python/docs/source/Tutorial_1.rst
  wrapping/python/docs/source/Tutorial_2.rst
  wrapping/python/docs/source/Tutorial_3.rst
  wrapping/python/docs/source/User_API.rst
Labels: documentation

#991 ENH/BUG : Update node based geometry find element family of functions
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/FeatureFaceCurvature.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/FindNRingNeighbors.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/LabelTriangleGeometry.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/LaplacianSmoothing.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ComputeFeatureSizesFilter.cpp
  src/simplnx/DataStructure/Geometry/EdgeGeom.cpp
  src/simplnx/DataStructure/Geometry/EdgeGeom.hpp
  src/simplnx/DataStructure/Geometry/HexahedralGeom.cpp
  src/simplnx/DataStructure/Geometry/HexahedralGeom.hpp
  src/simplnx/DataStructure/Geometry/IGeometry.hpp
  src/simplnx/DataStructure/Geometry/INodeGeometry1D.hpp
  src/simplnx/DataStructure/Geometry/INodeGeometry2D.hpp
  src/simplnx/DataStructure/Geometry/INodeGeometry3D.hpp
  src/simplnx/DataStructure/Geometry/ImageGeom.cpp
  src/simplnx/DataStructure/Geometry/ImageGeom.hpp
  src/simplnx/DataStructure/Geometry/QuadGeom.cpp
  src/simplnx/DataStructure/Geometry/QuadGeom.hpp
  src/simplnx/DataStructure/Geometry/RectGridGeom.cpp
  src/simplnx/DataStructure/Geometry/RectGridGeom.hpp
  src/simplnx/DataStructure/Geometry/TetrahedralGeom.cpp
  src/simplnx/DataStructure/Geometry/TetrahedralGeom.hpp
  src/simplnx/DataStructure/Geometry/TriangleGeom.cpp
  src/simplnx/DataStructure/Geometry/TriangleGeom.hpp
  src/simplnx/DataStructure/Geometry/VertexGeom.cpp
  src/simplnx/DataStructure/Geometry/VertexGeom.hpp
  src/simplnx/Utilities/GeometryHelpers.hpp
  test/DataStructTest.cpp
Labels: bug, enhancement

#1000 BUG: Update geometry find element functions to use static casting
  src/simplnx/DataStructure/Geometry/EdgeGeom.cpp
  src/simplnx/DataStructure/Geometry/HexahedralGeom.cpp
  src/simplnx/DataStructure/Geometry/ImageGeom.cpp
  src/simplnx/DataStructure/Geometry/QuadGeom.cpp
  src/simplnx/DataStructure/Geometry/RectGridGeom.cpp
  src/simplnx/DataStructure/Geometry/TetrahedralGeom.cpp
  src/simplnx/DataStructure/Geometry/TriangleGeom.cpp
  src/simplnx/DataStructure/Geometry/VertexGeom.cpp
Labels: bug

#984 FILTER : SliceTriangleGeometry & CreateAMScanPaths
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/docs/CreateAMScanPathsFilter.md
  src/Plugins/SimplnxCore/docs/Images/CreateAMScanVectors_1.png
  src/Plugins/SimplnxCore/docs/Images/CreateAMScanVectors_2.png
  src/Plugins/SimplnxCore/docs/Images/CreateAMScanVectors_3.png
  src/Plugins/SimplnxCore/docs/Images/CreateAMScanVectors_4.png
  src/Plugins/SimplnxCore/docs/Images/CreateAMScanVectors_5.png
  src/Plugins/SimplnxCore/docs/Images/SliceTriangleGeometry_1.png
  src/Plugins/SimplnxCore/docs/Images/SliceTriangleGeometry_2.png
  src/Plugins/SimplnxCore/docs/SliceTriangleGeometryFilter.md
  src/Plugins/SimplnxCore/pipelines/CreateScanVectors.d3dpipeline
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/CreateAMScanPaths.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/CreateAMScanPaths.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/SliceTriangleGeometry.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/SliceTriangleGeometry.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/CreateAMScanPathsFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/CreateAMScanPathsFilter.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/SliceTriangleGeometryFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/SliceTriangleGeometryFilter.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/SimplnxCoreLegacyUUIDMapping.hpp
  src/Plugins/SimplnxCore/test/CMakeLists.txt
  src/Plugins/SimplnxCore/test/CreateAMScanPathsTest.cpp
  src/Plugins/SimplnxCore/test/SliceTriangleGeometryTest.cpp
  src/simplnx/DataStructure/DataPath.cpp
  src/simplnx/DataStructure/Geometry/EdgeGeom.cpp
  src/simplnx/DataStructure/Geometry/EdgeGeom.hpp
  src/simplnx/DataStructure/Geometry/HexahedralGeom.cpp
  src/simplnx/DataStructure/Geometry/HexahedralGeom.hpp
  src/simplnx/DataStructure/Geometry/INodeGeometry1D.hpp
  src/simplnx/DataStructure/Geometry/QuadGeom.cpp
  src/simplnx/DataStructure/Geometry/QuadGeom.hpp
  src/simplnx/DataStructure/Geometry/TetrahedralGeom.cpp
  src/simplnx/DataStructure/Geometry/TetrahedralGeom.hpp
  src/simplnx/DataStructure/Geometry/TriangleGeom.cpp
  src/simplnx/DataStructure/Geometry/TriangleGeom.hpp
  src/simplnx/DataStructure/Geometry/VertexGeom.cpp
  src/simplnx/Utilities/GeometryUtilities.hpp
  test/DataPathTest.cpp
Labels: bug, Filter

#1006 ENH: Include additional geometry examples and tests.
  src/Plugins/SimplnxCore/pipelines/CreateEdgeGeom.d3dpipeline
  src/Plugins/SimplnxCore/pipelines/CreateHexahedralGeom.d3dpipeline
  src/Plugins/SimplnxCore/pipelines/CreateImageGeom.d3dpipeline
  src/Plugins/SimplnxCore/pipelines/CreateQuadGeom.d3dpipeline
  src/Plugins/SimplnxCore/pipelines/CreateRectGridGeom.d3dpipeline
  src/Plugins/SimplnxCore/pipelines/CreateTetrahedralGeom.d3dpipeline
  src/Plugins/SimplnxCore/pipelines/CreateTriangleGeom.d3dpipeline
  src/Plugins/SimplnxCore/pipelines/CreateVertexGeom.d3dpipeline
  test/CMakeLists.txt
  test/Data/HexaConnectivity.csv
  test/Data/HexaVertexCoordinates.csv
  test/Data/RectGridBounds.csv
  test/Data/TetraConnectivity.csv
  test/Data/TetraVertexCoordinates.csv
  test/H5Test.cpp
  wrapping/python/examples/scripts/geometry_examples.py
Labels: enhancement
