Repository BlueQuartzSoftware/simplnx, pull requests merged in 2025-02, with the labels that each got.

#1201 BUG FIX: Read H5Ebsd File now reports image geometry bounds correctly.
  src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/ReadH5EbsdFilter.cpp
  src/simplnx/Utilities/ImageRotationUtilities.cpp
  src/simplnx/Utilities/ImageRotationUtilities.hpp
Labels: bug

#1202 BUG: Fixes bug where CreateDataArrayAdvanced initializes the arrays twice
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/CreateDataArrayAdvancedFilter.cpp
Labels: bug

#1205 BUG FIX: CSV Reader now reads UTF-8 text files correctly.
  src/simplnx/Utilities/FileUtilities.cpp
  src/simplnx/Utilities/FileUtilities.hpp
Labels: bug

#1216 ENH: Allows users to store the transform matrix from the ApplyTransformationToGeometry
  src/Plugins/SimplnxCore/docs/ApplyTransformationToGeometryFilter.md
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/ApplyTransformationToGeometry.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/ApplyTransformationToGeometry.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ApplyTransformationToGeometryFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ApplyTransformationToGeometryFilter.hpp
Labels: enhancement

#1210 FILTER: Combine Node Based Geometries
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/docs/CombineNodeBasedGeometriesFilter.md
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/CombineNodeBasedGeometries.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/CombineNodeBasedGeometries.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/CombineNodeBasedGeometriesFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/CombineNodeBasedGeometriesFilter.hpp
  src/Plugins/SimplnxCore/test/CMakeLists.txt
  src/Plugins/SimplnxCore/test/CombineNodeBasedGeometriesTest.cpp
Labels: Filter
