Repository BlueQuartzSoftware/simplnx, pull requests merged in 2025-03, with the labels that each got.

#1188 BUG: Changes the Face Label value to -1 for boundary triangles in SurfaceNets
  src/Plugins/SimplnxCore/docs/QuickSurfaceMeshFilter.md
  src/Plugins/SimplnxCore/docs/SurfaceNetsFilter.md
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/SurfaceNets.cpp
Labels: bug, enhancement

#1233 BUG: Removes number of triangles guess from QuickMesh and SurfaceNets
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/QuickSurfaceMeshFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/SurfaceNetsFilter.cpp
Labels: bug

#1242 FILT: Adds 'Write SPParks Sites File'
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/docs/WriteSPParksSitesFilter.md
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/WriteSPParksSites.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/WriteSPParksSites.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/WriteSPParksSitesFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/WriteSPParksSitesFilter.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/SimplnxCoreLegacyUUIDMapping.hpp
  src/Plugins/SimplnxCore/test/CMakeLists.txt
  src/Plugins/SimplnxCore/test/WriteSPParksSitesTest.cpp
Labels: Filter

#1230 ENH: Dream3dImportParameter supports additional import options.
  src/Plugins/OrientationAnalysis/test/MergeTwinsTest.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/ReadDREAM3DFilter.cpp
  src/Plugins/SimplnxCore/test/DREAM3DFileTest.cpp
  src/Plugins/SimplnxCore/test/PartitionGeometryTest.cpp
  src/Plugins/SimplnxCore/wrapping/python/simplnxpy.cpp
  src/simplnx/Filter/Actions/ImportH5ObjectPathsAction.cpp
  src/simplnx/Filter/Actions/ImportH5ObjectPathsAction.hpp
  src/simplnx/Parameters/Dream3dImportParameter.cpp
  src/simplnx/Parameters/Dream3dImportParameter.hpp
  wrapping/python/docs/source/Developer_API.rst
  wrapping/python/docs/source/Python_Introduction.rst
  wrapping/python/docs/source/User_API.rst
  wrapping/python/examples/notebooks/import_d3d.ipynb
  wrapping/python/examples/pipelines/OrientationAnalysis/01_Small_IN100_Morphological_Statistics.py
  wrapping/python/examples/pipelines/OrientationAnalysis/01_Small_IN100_Quick_Mesh.py
  wrapping/python/examples/pipelines/OrientationAnalysis/02_Small_IN100_Smooth_Mesh.py
  wrapping/python/examples/pipelines/OrientationAnalysis/03_Small_IN100_Mesh_Statistics.py
  wrapping/python/examples/pipelines/OrientationAnalysis/04_Small_IN100_GBCD.py
  wrapping/python/examples/pipelines/OrientationAnalysis/05_Small_IN100_Crystallographic_Statistics.py
  wrapping/python/examples/pipelines/OrientationAnalysis/05_Small_IN100_GBCD_Metric.py
  wrapping/python/examples/pipelines/OrientationAnalysis/AvizoWriters.py
  wrapping/python/examples/pipelines/OrientationAnalysis/ComputeBiasedFeatures.py
  wrapping/python/examples/pipelines/OrientationAnalysis/ComputeBoundaryCells.py
  wrapping/python/examples/pipelines/OrientationAnalysis/ComputeGBCD-GBPDMetricBased.py
  wrapping/python/examples/pipelines/OrientationAnalysis/VtkRectilinearGridWriter.py
  wrapping/python/examples/scripts/import_d3d.py
  wrapping/python/plugins/ExamplePlugin/src/ExamplePlugin/ExampleFilter1.py
Labels: enhancement
