Repository BlueQuartzSoftware/simplnx, pull requests merged in 2025-01, with the labels that each got.

#1168 FILTER: Add WriteNodesAndElementsFiles filter
  src/Plugins/SimplnxCore/CMakeLists.txt
  src/Plugins/SimplnxCore/docs/WriteNodesAndElementsFilesFilter.md
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/WriteNodesAndElementsFiles.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/Algorithms/WriteNodesAndElementsFiles.hpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/WriteNodesAndElementsFilesFilter.cpp
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/WriteNodesAndElementsFilesFilter.hpp
  src/Plugins/SimplnxCore/test/CMakeLists.txt
  src/Plugins/SimplnxCore/test/WriteNodesAndElementsFilesTest.cpp
Labels: Filter

#1167 ENH: Use GetAllGeomTypes() method in PartitionGeometryFilter.
  src/Plugins/SimplnxCore/src/SimplnxCore/Filters/PartitionGeometryFilter.cpp
Labels: enhancement

#1166 BUG FIX: MeshIO writer code now writes cell data properly.
  wrapping/python/plugins/NXDataAnalysisToolkit/src/NXDataAnalysisToolkit/utilities/meshio_utilities.py
Labels: bug

#1171 BUG: Defends against malformed preferences JSON file or Json content within the file
  src/simplnx/Core/Preferences.cpp
Labels: bug
